name: Python Testing
on:
  push:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Get latest code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2

    - name: Install dependencies
      run: |
        ls; python -m pip install --upgrade pip pip install -r requirements.txt
    
    - name: Run tests
      run: |
        ./tests.sh 